url: https://AtsushiOhori.github.io
permalink: pretty
highlighter: rouge
relative_links:
  enabled: true
  collections: true
sass:
  style: compressed
defaults:
  -
    scope:
      path: en
    values:
      menuScope: en
      lang: en
  -
    scope:
      path: ja
    values:
      menuScope: ja
      lang: ja
  -
    scope:
      path: ja/texts
    values:
      menuScope: texts
      lang: ja
  -
    scope:
      path: ja/texts/authorProfile
    values:
      menuScope: texts
      lang: ja
  -
    scope:
      path: ja/texts/compiler
    values:
      menuScope: compiler
      lang: ja
  -
    scope:
      path: ja/texts/standard-ml
    values:
      menuScope: standard-ml
      lang: ja
  -
    scope:
      path: ja/texts/ml-practice
    values:
      menuScope: ml-practice
      lang: ja
  -
    scope:
      path: ja/texts/kisoriron
    values:
      menuScope: kisoriron
      lang: ja
  -
    scope:
      path: ja/texts/keisankigairon
    values:
      menuScope: keisankigairon
      lang: ja
  -
    scope:
      path: ja/texts/csnyumon
    values:
      menuScope: csnyumon
      lang: ja
  -
    scope:
      path: ja/videos
    values:
      menuScope: videos
      lang: ja
  -
    scope:
      path: ja/videos/instructorProfile
    values:
      menuScope: videos
      lang: ja
  -
    scope:
      path: ja/videos/playlist
    values:
      menuScope: playlist
      lang: ja
  -
    scope:
      path: ja/videos/playlist/hyougen
    values:
      menuScope: hyougen
      lang: ja
  -
    scope:
      path: ja/videos/playlist/gairon
    values:
      menuScope: gairon
      lang: ja
  -
    scope:
      path: ja/videos/playlist/smlsharpAndC
    values:
      menuScope: smlsharpAndC
      lang: ja
  -
    scope:
      path: ja/videos/playlist/DBProgramming
    values:
      menuScope: DBProgramming
      lang: ja
  -
    scope:
      path: ja/videos/playlist/compilerVideo
    values:
      menuScope: compilerVideo
      lang: ja
  -
    scope:
      path: ja/videos/playlist/progModel
    values:
      menuScope: progModel
      lang: ja
  -
    scope:
      path: ja/videos/playlist/typeInf
    values:
      menuScope: typeInf
      lang: ja
  -
    scope:
      path: ja/videos/playlist/progEnv
    values:
      menuScope: progEnv
      lang: ja
  -
    scope:
      path: ja/videos/playlist/typedLambda
    values:
      menuScope: typedLambda
      lang: ja
  -
    scope:
      path: ja/videos/playlist/appliedLambda
    values:
      menuScope: appliedLambda
      lang: ja
  -
    scope:
      path: ja/videos/playlist/saisyuKougi
    values:
      menuScope: saisyuKougi
      lang: ja
